spring:
  application:
    name: kopring

  profiles:
    active: local

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:core;MODE=MySQL;
    username: sa
    password: sa

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
        ddl-auto: create
        show_sql: true
        format_sql: true
        highlight_sql: true
